---
title: "Political Factions"
subtitle: "Subtitle"
#author: "Nicola Casarin"
institute: "UNIMI"
#date: "`r format(Sys.time(), '%Y %B %d')`"
#fontsize: 12pt
output: 
  pdf_document:
    latex_engine: pdflatex
    #keep_tex: yes
    includes:
      in_header: preamble.tex
bibliography: references.bib
csl: apa.csl
---


```{r setup and library loading, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SPARQL)
library(tidyverse)
library(stringr)
library(here)
library(vroom)
library(lubridate)
library(igraph)
library(stringr)
`%!in%` <- Negate(`%in%`) # "not in" function declaration
```

# Introduction

In this short analysis, we use the open data from the Chamber of the Deputies of the Italian Parliament to investigate the legislative co-sponsorship of the members of the Chamber of the Deputies. The analysis would cover the legislative process that ensued under Conte I and Conte II cabinets within the legislature XVIII of Italy.

The analysis aims to understand the presence of political factions underlying the legislative process in the Lower chamber of the Italian Parliament by employing social network analysis techniques. Moreover, we will analyse the cooperative behaviour of the Parliament parties computing the *intra-opposition party bill differentiation*, as shown by De Giorgi & Dias [-@de_giorgi_2018].

Other sources

Lastly, this project also strives to create a fully reproducible workflow documented, commented and hosted in a public Github repository.


# Methods


# Results

# Discussion

# References